${ORACLE_HOME_ARG}/bin/dbca -silent -createDatabase \
-templateName General_Purpose.dbc \
-gdbname ${CDB_NAME_ARG} \
-sid ${CDB_NAME_ARG} \
-responseFile NO_VALUE \
-characterSet AL32UTF8 \
-sysPassword SysPassword1 \
-systemPassword SysPassword1 \
-createAsContainerDatabase true \
-numberOfPDBs 1 \
-pdbName ${PDB_NAME_ARG} \
-pdbAdminPassword PdbPassword1 \
-databaseType MULTIPURPOSE \
-automaticMemoryManagement false \
-totalMemory 1500 \
-storageType FS \
-datafileDestination ${ORACLE_DATA_ARG} \
-redoLogFileSize 50 \
-emConfiguration NONE \
-ignorePreReqs
